---
version: '2'
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: training
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    network_mode: host
    ports:
        - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
      - "default:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    network_mode: host
    ports:
        - "9092:9092"
        - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 #, SSL://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
      - "default:127.0.0.1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Global Volumes
volumes:
  postgres-data:

        #  schema-registry:
        #    image: confluentinc/cp-schema-registry:4.0.0
        # network_mode: host
        # environment:
        #  SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:2181
        #  SCHEMA_REGISTRY_HOST_NAME: localhost
        #  SCHEMA_REGISTRY_LISTENERS: http://localhost:8081

